"""R32 bracket allocation and knockout round simulation for WC 2026.

Responsibilities:
  1. assign_thirds_to_slots(): maps 8 qualifying third-place groups to the
     8 bracket slots in bracket_map.json.  Checks pre-computed
     annex_c_combinations first; falls back to bipartite matching.
  2. resolve_r32(): builds the 16 R32 matchups by resolving slot codes
     ("1E", "2A", "3ABCDF") to actual team names.
  3. simulate_ko_match(): 90-min Poisson draw -> extra time -> penalties.
  4. simulate_knockout(): chains R32->R16->QF->SF->Final and returns
     round-by-round winners.
  5. generate_annex_c_table(): pre-computes all C(12,8)=495 slot assignments
     and writes them to bracket_map.json (run once; stored for O(1) lookup).
"""

from __future__ import annotations

import json
import logging
from itertools import combinations
from pathlib import Path
from typing import TYPE_CHECKING, Any

import numpy as np
from numpy.random import Generator
from scipy.optimize import linear_sum_assignment

if TYPE_CHECKING:
    from src.model.poisson import MatchSimulator
    from src.sim.standings import GroupResult

logger = logging.getLogger(__name__)

_ALL_GROUPS = list("ABCDEFGHIJKL")
_BRACKET_MAP_PATH = Path("data/bracket_map.json")


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------


def load_bracket_map(path: str | Path = _BRACKET_MAP_PATH) -> dict[str, Any]:
    with open(path) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Annex C: bipartite matching fallback
# ---------------------------------------------------------------------------


def _bipartite_matching(
    qualifying_groups: list[str],
    slot_candidates: dict[str, list[str]],
) -> dict[str, str]:
    """Assign groups to slots via the Hungarian algorithm.

    Cost matrix: 0 for a valid (group, slot) pair, 1e9 for infeasible.

    Returns:
        dict[group_letter, slot_code]

    Raises:
        ValueError if no valid assignment exists.
    """
    groups = sorted(qualifying_groups)
    slots = list(slot_candidates.keys())
    n = len(groups)

    cost = np.full((n, n), 1e9)
    for i, grp in enumerate(groups):
        for j, slot in enumerate(slots):
            if grp in slot_candidates[slot]:
                cost[i, j] = 0.0

    row_ind, col_ind = linear_sum_assignment(cost)

    if cost[row_ind, col_ind].sum() > 0:
        raise ValueError(
            f"No valid slot assignment for qualifying groups: {qualifying_groups}. "
            "This combination violates the bracket constraints defined in bracket_map.json."
        )

    return {groups[i]: slots[j] for i, j in zip(row_ind, col_ind, strict=False)}


def assign_thirds_to_slots(
    qualifying_groups: list[str],
    bracket_map: dict[str, Any],
) -> dict[str, str]:
    """Map each qualifying third-place group to a specific R32 slot.

    Checks annex_c_combinations for a pre-computed entry first; falls back
    to bipartite matching.  The pre-computed table is generated by
    generate_annex_c_table() and stored in bracket_map.json.

    NOTE: The pre-computed assignments use bipartite matching, NOT the
    official FIFA Annex C table (which is unpublished).  All assignments are
    valid (each group goes to a slot listing that group), but may differ from
    FIFA's official choice.

    Args:
        qualifying_groups: 8 group letters that produced best-third qualifiers.
        bracket_map: Loaded bracket_map.json dict.

    Returns:
        dict[group_letter, slot_code]
    """
    slot_candidates = bracket_map["third_place_slot_candidates"]
    annex_c = bracket_map.get("annex_c_combinations", {})
    combo_key = "".join(sorted(qualifying_groups))

    if combo_key in annex_c:
        return annex_c[combo_key]

    logger.debug(
        "Annex C: combination %s not in pre-computed table; using bipartite matching.",
        combo_key,
    )
    return _bipartite_matching(sorted(qualifying_groups), slot_candidates)


# ---------------------------------------------------------------------------
# R32 matchup resolution
# ---------------------------------------------------------------------------


def resolve_r32(
    group_results: dict[str, GroupResult],
    best_third_groups: list[str],
    bracket_map: dict[str, Any],
) -> list[tuple[str, str]]:
    """Build the 16 R32 matchups from group results and best-third qualifiers.

    Args:
        group_results: dict[group_id, GroupResult] for all 12 groups.
        best_third_groups: 8 qualifying group letters.
        bracket_map: Loaded bracket_map.json.

    Returns:
        List of 16 (team_a, team_b) tuples in R32_01..R32_16 order.
    """
    group_to_slot = assign_thirds_to_slots(best_third_groups, bracket_map)
    slot_to_group = {slot: grp for grp, slot in group_to_slot.items()}

    def resolve_code(code: str) -> str:
        rank = code[0]
        if rank == "1":
            return group_results[code[1:]].first
        if rank == "2":
            return group_results[code[1:]].second
        # Third-place slot: code is a full slot key like "3ABCDF"
        return group_results[slot_to_group[code]].third

    return [
        (resolve_code(t["team_a"]), resolve_code(t["team_b"])) for t in bracket_map["r32_templates"]
    ]


# ---------------------------------------------------------------------------
# Knockout match simulation
# ---------------------------------------------------------------------------


def simulate_ko_match(
    team_a: str,
    team_b: str,
    strength: dict[str, float],
    model: MatchSimulator,
    rng: Generator,
    cfg: dict[str, Any],
) -> str:
    """Simulate one KO match through to a definite winner.

    Phases:
      1. 90 min: Poisson draw with caution factor applied.
      2. Extra time (30 min): lambda scaled by extra_time_duration_fraction.
      3. Penalties: Bernoulli with base 0.5 + small strength tilt.

    All matches are neutral (no home-advantage term).
    """
    alpha = float(cfg["goals_model"]["intercept"])
    beta = float(cfg["goals_model"]["slope"])
    lam_cap = float(cfg["goals_model"].get("lambda_cap", 6.0))
    lam_floor = float(cfg["goals_model"].get("lambda_floor", 0.1))
    caution = float(cfg["knockout"]["caution_factor"])
    et_frac = float(cfg["knockout"]["extra_time_duration_fraction"])
    p_base = float(cfg["knockout"]["penalty_base"])
    p_tilt = float(cfg["knockout"]["penalty_strength_tilt"])
    p_tilt_max = float(cfg["knockout"]["penalty_strength_tilt_max"])

    elo_diff = strength[team_a] - strength[team_b]

    # 90 minutes
    lam_a = float(np.clip(np.exp(alpha + beta * elo_diff) * caution, lam_floor, lam_cap))
    lam_b = float(np.clip(np.exp(alpha - beta * elo_diff) * caution, lam_floor, lam_cap))
    ga, gb = model.simulate_match(lam_a, lam_b, rng)
    if ga != gb:
        return team_a if ga > gb else team_b

    # Extra time
    lam_et_a = float(np.clip(lam_a * et_frac, lam_floor, lam_cap))
    lam_et_b = float(np.clip(lam_b * et_frac, lam_floor, lam_cap))
    eta, etb = model.simulate_match(lam_et_a, lam_et_b, rng)
    total_a, total_b = ga + eta, gb + etb
    if total_a != total_b:
        return team_a if total_a > total_b else team_b

    # Penalties: base probability + tilt by Elo difference
    p_a = float(p_base + np.clip(elo_diff / 100.0 * p_tilt, -p_tilt_max, p_tilt_max))
    return team_a if rng.random() < p_a else team_b


# ---------------------------------------------------------------------------
# Full bracket simulation
# ---------------------------------------------------------------------------


def _play_round(
    matchups: list[tuple[str, str]],
    strength: dict[str, float],
    model: MatchSimulator,
    rng: Generator,
    cfg: dict[str, Any],
) -> list[str]:
    return [simulate_ko_match(a, b, strength, model, rng, cfg) for a, b in matchups]


def simulate_knockout(
    r32_matchups: list[tuple[str, str]],
    strength: dict[str, float],
    model: MatchSimulator,
    rng: Generator,
    cfg: dict[str, Any],
) -> dict[str, Any]:
    """Simulate all KO rounds from R32 to the Final.

    Bracket progression: consecutive pairing at each round.
      R32 (16) -> R16 (8) -> QF (4) -> SF (2) -> Final (1)

    Args:
        r32_matchups: 16 (team_a, team_b) tuples from resolve_r32().
        strength: team_name -> composite strength value.
        model: MatchSimulator.
        rng: NumPy Generator.
        cfg: Parsed config dict.

    Returns:
        {
            "r32": [16 winners],
            "r16": [8 winners],
            "qf":  [4 winners],
            "sf":  [2 winners],
            "champion": str,
        }
    """
    if len(r32_matchups) != 16:
        raise ValueError(f"Expected 16 R32 matchups, got {len(r32_matchups)}")

    r32 = _play_round(r32_matchups, strength, model, rng, cfg)
    r16 = _play_round([(r32[i], r32[i + 1]) for i in range(0, 16, 2)], strength, model, rng, cfg)
    qf = _play_round([(r16[i], r16[i + 1]) for i in range(0, 8, 2)], strength, model, rng, cfg)
    sf = _play_round([(qf[i], qf[i + 1]) for i in range(0, 4, 2)], strength, model, rng, cfg)
    champion = simulate_ko_match(sf[0], sf[1], strength, model, rng, cfg)

    return {"r32": r32, "r16": r16, "qf": qf, "sf": sf, "champion": champion}


# ---------------------------------------------------------------------------
# Annex C pre-computation
# ---------------------------------------------------------------------------


def generate_annex_c_table(
    bracket_map: dict[str, Any] | None = None,
    write: bool = True,
    path: str | Path = _BRACKET_MAP_PATH,
) -> dict[str, dict[str, str]]:
    """Pre-compute slot assignments for all C(12,8)=495 group combinations.

    Uses bipartite matching (_bipartite_matching) for each combination.
    Writes the result back to bracket_map.json when write=True.

    NOTE: These assignments are algorithmically valid but are NOT the official
    FIFA Annex C table (which is unpublished).  Replace annex_c_combinations in
    bracket_map.json with the official table if/when FIFA publishes it.

    Returns:
        dict[combo_key, dict[group, slot]]  (495 entries)
    """
    if bracket_map is None:
        bracket_map = load_bracket_map(path)

    slot_candidates = bracket_map["third_place_slot_candidates"]
    table: dict[str, dict[str, str]] = {}

    for combo in combinations(_ALL_GROUPS, 8):
        key = "".join(combo)
        table[key] = _bipartite_matching(list(combo), slot_candidates)

    if write:
        bracket_map["annex_c_combinations"] = table
        with open(path, "w") as f:
            json.dump(bracket_map, f, indent=2)
        logger.info("Wrote %d Annex C entries to %s", len(table), path)

    return table


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    tbl = generate_annex_c_table()
    print(f"Generated {len(tbl)} Annex C combinations.")
    # Spot-check
    sample = "ABCDEFGH"
    print(f"  {sample} -> {tbl[sample]}")
